name:  test_pullrequest

on:
  pull_request:
    branches: dev

 

  schedule:
    # * is a special character in YAML so you have to quote this string
    ### Every 12 hours
    - cron:  '0 */1 * * *' 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1


    ##### Log Start  ######################################################
    - name: ssh_gen
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.GIT_RSA }}
                
    - name: log_start
      run: |
           cd /home/runner/work/mlmodels/  && git clone git@github.com:arita37/mlmodels_store.git  &&  ls && pwd
           cd /home/runner/work/mlmodels/mlmodels/
    ########################################################################

            
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-venv-mlmodels-${{ hashFiles('**/requirements_fake.txt') }}


    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy==1.18.2   black
      
    - name: Install repo requirements 1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements.txt


    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements_fake.txt


    - name: Install repo
      run: pip install -e . -r requirements.txt   --no-deps


    - name: run_basic_check.py
      run: python run_basic_check.py


    ########  Test running 
    ##### Please change BELOW to your model name  
    #- name: matchzoo
    #  run: black -l 120  --py36 --check --fast  .


    ##### Please change BELOW to your model name  
    - name: ml_test Pull Request
      run: ml_test --do test_pullrequest     2>&1 | tee -a  cd /home/runner/work/mlmodels/mlmodels_store/log_pullrequest/log_$(date '+%Y-%m-%d_%H-%M-%S-%3N').py


    - name: log_gitcommit
      run: ml_test --do log_remote_push






      
